//WebExercises POST test
POST http://localhost:3003/exercises
Content-type: application/json

{
  "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
  "target": 2.5
}

###

//WebExercises POST test
POST http://localhost:3003/exercises
Content-type: application/json

{
  "daily_exercises": 1,
  "target": 2.5
}

###

//WebExercises POST test
POST http://localhost:3003/exercises
Content-type: application/json

{
  "daily_exercises": [1],
  "target": 2.5
}

###
//POST test: missing daily_exercises
POST http://localhost:3003/exercises
Content-type: application/json

{
  "target": 2.5
}

###
//POST test: wrong format for daily_exercises
POST http://localhost:3003/exercises
Content-type: application/json

{
  "daily_exercises": "test",
  "target": 2.5
}