//kaikkien blogien pyytäminen
GET http://localhost:3003/api/blogs

###
//blogin lisääminen tietokantaan
POST http://localhost:3003/api/blogs
Content-type: application/json

{
  "title": "Very interesting blog",
  "author": "Someone smart",
  "url": "url of the blog would be here",
  "likes": 125
}

###
//blogin lisääminen tietokantaan ilman titleä
POST http://localhost:3003/api/blogs
Content-type: application/json

{
  "author": "Someone smart",
  "url": "url of the blog would be here",
  "likes": 125
}

###
//blogin lisääminen tietokantaan userId:n kanssa
POST http://localhost:3003/api/blogs
Content-type: application/json

{
  "title": "Very interesting blog",
  "author": "Someone smart",
  "url": "url of the blog would be here",
  "likes": 125,
  "userId": "6005f2d8e1600e81c8dda690"
}

###
//deleten testaaminen
DELETE http://localhost:3003/api/blogs/600709586cb33c35cbb5a261

###
//PUT pyyntö
PUT http://localhost:3003/api/blogs/60034aa396de4d3f0bebb172
Content-Type: application/json

{
    "likes": 5
}

###
//PUT pyyntö, päivitä liket ja titteli
PUT http://localhost:3003/api/blogs/60034aa396de4d3f0bebb172
Content-Type: application/json

{
    "title": "New and very smart title",
    "likes": 100
}
###
//PUT pyyntö väärään id:hen
PUT http://localhost:3003/api/blogs/123456
Content-Type: application/json

{
    "title": "New and very smart title",
    "likes": 100
}